### ISSUE TITLE
Reference Error with Babel

### ISSUE THREAD

**Issue by steventsao** [LukeLin/data-structure-with-js#28]
`ReferenceError: [BABEL] /Users/.../Array/CrossList.es6: Using removed Babel 5 option: base.optional   Put the specific transforms you want in the 'plugins' option`

Run into this reference error while running Gulp. Does this mean I need to change my Babel version? If so, where? Thanks!

**Comment by LukeLin** [comment]
Done! I've replaced gulp with webpack for building files.And each module has exact version in package.json. Hope it helps u.

**Comment by LukeLin** [comment]
Sorry about the lated commit. I've been busy working recently...
